### ISSUE TITLE
detecting & signaling namespace collision due to redefinition of standard types

### ISSUE THREAD

**Issue by fredkgit** [Orange-OpenSource/Cloudnet-TOSCA-toolbox#13]
for instance, the redefinition eComp did a few years ago for ONAP in tosca 1.1 templates

**Comment by JLCoulin** [comment]
Closed with merge [ff54839](https://github.com/Orange-OpenSource/Cloudnet-TOSCA-toolbox/commit/ff54839b006840b2923ebc386c84f35d93384728)
