### ISSUE TITLE
capabilities to relationship association

### ISSUE THREAD

**Issue by fredkgit** [Orange-OpenSource/Cloudnet-TOSCA-toolbox#14]
Currently, we have 'ERROR: relationship type undefined' when the relationship is not explicitly defined in node template.
Is it possible to skim through all the available type definition to list associations between capabilities and relationships so the program goes, the translation to Alloy and diagrams are fine? Also the user would just get a warning?

**Comment by JLCoulin** [comment]
Closed with merge [ff54839](https://github.com/Orange-OpenSource/Cloudnet-TOSCA-toolbox/commit/ff54839b006840b2923ebc386c84f35d93384728)
