### ISSUE TITLE
handling requirements without value

### ISSUE THREAD

**Issue by fredkgit** [Orange-OpenSource/Cloudnet-TOSCA-toolbox#15]
Currently unassigned

 requirements yield an error " None is not valid under any of the given schemas! "

In the ETSI/NFV case, it is common to find such requirements with a comment instead of a value.
This is generally because the actual value is not known before deployment time (e.g. the information saying  which other VNF a VNF may be connected to inside an NS is provided at NS creation time.

Can we make it a warning instead of an error?

[empty_reqs.txt](https://github.com/Orange-OpenSource/Cloudnet-TOSCA-toolbox/files/5604258/empty_reqs.txt)

**Comment by philippemerle** [comment]
@fredkgit I propose to close this issue because declaring a requirement with a null value is a grammatical error.

**Comment by fredkgit** [comment]
Ok
