### ISSUE TITLE
full check of TOSCA constraints

### ISSUE THREAD

**Issue by fredkgit** [Orange-OpenSource/Cloudnet-TOSCA-toolbox#16]
Check that value assignments in templates meet all the constraints declared for the property in type definitions (provided by users).
For instance, in the following case, levels has at least one entry:
properties:
  levels:
    type: map
    required: true
    entry_schema:
      type: tosca.datatypes.nfv.InstantiationLevel
    constraints:
     - min_length: 1
This may be part of the issue on type checking enhancement,. However, I add it as an issue because it was experienced & recorded.

**Comment by philippemerle** [comment]
This issue requires a lot of developments and will be resolved in some months.

**Comment by JLCoulin** [comment]
closed with commit [ff54839]( https://github.com/Orange-OpenSource/Cloudnet-TOSCA-toolbox/commit/ff54839b006840b2923ebc386c84f35d93384728)
