### ISSUE TITLE
Full path needed for CLOUDNET_BINDIR

### ISSUE THREAD

**Issue by pmjordan** [Orange-OpenSource/Cloudnet-TOSCA-toolbox#38]
The install instructions include setting a value for CLOUDNET_BINDIR with a relative pathname. I found that this gave an docker error

docker: Error response from daemon: create ../../bin/cloudnet: "../../bin/cloudnet" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.

This was resolved when I set the value of CLOUDNET_BINDIR to a full pathname.

**Comment by philippemerle** [comment]
Thank you @pmjordan to report us this issue in the documentation. This was corrected by commit https://github.com/Orange-OpenSource/Cloudnet-TOSCA-toolbox/commit/48b04a70bf7c1c902494146e9950197e6d9059de. Now the CLOUDNET_BINDIR variable can be set to either an absolute path or relative path.
