### ISSUE TITLE
Parameter refinements not supported in capability type defintions

### ISSUE THREAD

**Issue by pmjordan** [Orange-OpenSource/Cloudnet-TOSCA-toolbox#39]
My TOSCA template contains 
`capability_types:
  TMFAPI:
    derived_from: tosca.capabilities.Node
    description: a TMForum defined REST API
    properties:
      id:
        type: string
        description: the id e.g TMF632
      name:
        type: string
        description: the name, e.g. party

  TMF632:
    derived_from: TMFAPI 
    properties:
      id: TMF632
      name: party`

But this is rejected by your syntax checker with a message that       id: TMF632 and    name: party are unexpected. 
Perhaps this is because you are not expecting property defintion refinements as described in section 3.6.10.6 of TOSCA v1.3

**Comment by philippemerle** [comment]
Thank you @pmjordan to report us this issue.
As you indicated it, _refining property definitions_ is described in Section 3.6.10.6 of TOSCA v1.3.
Moreover, a property definition refinement is given at the end of Section 3.6.10.8 of TOSCA v1.3.

For information, your template is also not supported by both Puccini and xOpera tools. Anyway this is a bug to correct.

**Comment by philippemerle** [comment]
@pmjordan: Commit https://github.com/Orange-OpenSource/Cloudnet-TOSCA-toolbox/commit/b9a7f525aee258ad6330d0d0bb32a2027d4cc05d should resolve this issue. Could you try and report us if the issue is resolved or not?

**Comment by pmjordan** [comment]
Thank you for the fix. I confirm that the error messages are not produced in the latest version when I run locally. No doubt you are aware that the web service has not been updated.
Thank you also for the information. I will test and report to Puccini. I am not a user of xOpera but perhaps in the interests of achieving a consistent TOSCA implementation you could do so?

**Comment by philippemerle** [comment]
Thank @pmjordan for your reporting.
Unfortunately, the web portal is not currently updated continously.
I reported the issue to xOpera project: see https://github.com/xlab-si/xopera-opera/issues/246
