### ISSUE TITLE
Manage return codes when batch option used

### ISSUE THREAD

**Issue by JLCoulin** [Orange-OpenSource/Cloudnet-TOSCA-toolbox#4]
First of all define which return code we have
Then ask modification of the code to get the necessary return code figure out if the chain has finished correctly

**Comment by philippemerle** [comment]
In general, if no error then the exit code of a command is equals to 0, else the exit code is between 1 to 255.
I propose to use 1 to report any errors.
Do you agree?

**Comment by JLCoulin** [comment]
I think for the purpose of the CI chain to verify non regression, a more detailed return code level is needed.

I explain, in test yaml description we can imagine to test non regression could be :
- a file which generates no error
- a file which genarates warning(s)
- a file which generates error(s)

All these cases are one we know that they shoud produce these results

So I think we have to distinguish 3 level of return code : 
0 : ok
1 : warning
2 : error
or whatever values if some have specific meaning (to verify against https://tldp.org/LDP/abs/html/exitcodes.html or other documentation)

**Comment by philippemerle** [comment]
What return code when there are infos, warnings and errors simultaneously?

**Comment by JLCoulin** [comment]
Good question ;-)
What about returning the higher one ?

I have to think about the examples we have to set to be sure there is not a regression, but I'm not sure to

**Comment by JLCoulin** [comment]
I saw your new test directory, then I understand what you fired out by regression testing.

Do you mind if I / we fill in the syntax_checking.yaml file with errors we encounter ?

**Comment by philippemerle** [comment]
You are welcome to add other errors in syntax_checking.yaml.

**Comment by JLCoulin** [comment]
Thank you.
We can close this issue and continue working on the tests content.

**Comment by philippemerle** [comment]
Before closing this issue, I need to integrate the return codes expected by the portal.
0 for no problem, 1 for errors detected, 2 for fatal errors (nothing was generated).
