### ISSUE TITLE
Documentation error on get TOSCA diagrams

### ISSUE THREAD

**Issue by pmjordan** [Orange-OpenSource/Cloudnet-TOSCA-toolbox#44]
First the good news - I am now generating diagrams from my templates so thank you.

The README.md file contains 
`generate_tosca_diagrams tosca_diagrams/*.dot`

The user will be in a folder which contains Results/ToscaDiagrams so the command should be
`generate_tosca_diagrams Results/ToscaDiagrams/*.dot``

**Comment by philippemerle** [comment]
Excellent good news. Could @pmjordan share with us some generated diagrams?
Thank you for pointing out this documentation issue.
