### ISSUE TITLE
Processing inherited capability property values

### ISSUE THREAD

**Issue by pmjordan** [Orange-OpenSource/Cloudnet-TOSCA-toolbox#54]
When translating a file which has property assignments in capability definitions those assignments are not used when inherited by a node.

'translate example.txt
Translate example.txt...
[Info] example.txt: TOSCA syntax checking
[Info] example.txt: No service template catalog to load.
[Info] example.txt: TOSCA type checking...
[ERROR] example.txt@35,7:topology_template:node_templates:PrdCtgMgmt:capabilities:TMF620_capability - id required property unassigned!'

but this property is assigned in line 20

[example.txt](https://github.com/Orange-OpenSource/Cloudnet-TOSCA-toolbox/files/8358539/example.txt)

**Comment by philippemerle** [comment]
Thank @pmjordan for this bug report. I will correct it asap.

**Comment by philippemerle** [comment]
@pmjordan: could you check if the last commit resolves this issue?

**Comment by pmjordan** [comment]
Yes thank you for your quick work. The error message no longer appears.
