### ISSUE TITLE
Fix security issues in Python code

### ISSUE THREAD

**Issue by JLCoulin** [Orange-OpenSource/Cloudnet-TOSCA-toolbox#6]
The [ security tool bandit ](https://github.com/PyCQA/bandit) founds 4 medium issues related to yaml_load in follwing files : 
- bin/cloudnet/tosca/configuration.py:32
- bin/cloudnet/tosca/importers.py:182, 202, 240

[bandit-on-GithubCode.log](https://github.com/Orange-OpenSource/Cloudnet-TOSCA-toolbox/files/5588907/bandit-on-GithubCode.log)

**Comment by philippemerle** [comment]
@JLCoulin: could you check that this issue is resolved by commits https://github.com/Orange-OpenSource/Cloudnet-TOSCA-toolbox/commit/449515b212d4a6d7437c7dae4f969b9f9e352db7?

**Comment by JLCoulin** [comment]
It's ok.
Bandit does not report any message

**Comment by philippemerle** [comment]
Then you could close this issue.
