### ISSUE TITLE
default directory AND Flexibility of which module to execute 

### ISSUE THREAD

**Issue by JLCoulin** [Orange-OpenSource/Cloudnet-TOSCA-toolbox#68]
- Set the targetdirectory of Declarativeworkflow and uml2diagrams python module Results/xxxx
and change the readme.md

- Allow the ability to launch (or not) the different modules (DeclarativeWorkflowGenerator, AlloyGenerator, PlantUMLGenerator, NwdiagGenerator, ToscaDiagramGenerator, HOTGenerator)

**Comment by philippemerle** [comment]
By default, all generators are activated.

To desactivate  a generator, just configure `generation: false` in `tosca2cloudnet.yaml`., e.g.
```
DeclarativeWorkflows:
  generation: false
```
will desactivated the TOSCA Declarative Workflow Generator.

**Comment by philippemerle** [comment]
@JLCoulin : could you check that commit https://github.com/Orange-OpenSource/Cloudnet-TOSCA-toolbox/issues/68 does the expected job? If yes then you could close this issue.

**Comment by JLCoulin** [comment]
@philippemerle : I did a test and it works as expected, thank you.
