### ISSUE TITLE
Move type checking from generators to the TypeChecker  component

### ISSUE THREAD

**Issue by philippemerle** [Orange-OpenSource/Cloudnet-TOSCA-toolbox#7]
Currently, the Alloy generator implements some type checkings, i.e. produces some errors and warnings.
These type checkings must be moved to the TypeChecker component.

**Comment by JLCoulin** [comment]
Closed with merge [ff54839](https://github.com/Orange-OpenSource/Cloudnet-TOSCA-toolbox/commit/ff54839b006840b2923ebc386c84f35d93384728)
